### ISSUE TITLE
Isolates messaging

### ISSUE THREAD

**Issue by Sitiritis** [rmawatson/flutter_isolate#10]
Is there a way to send a message from the main isolate to the created Flutter isolate?

**Comment by rmawatson** [comment]
pass a sendPort in when you spawn it. Exactly the same as you would with a regular isolate

**Comment by Sitiritis** [comment]
> pass a sendPort in when you spawn it. Exactly the same as you would with a regular isolate

```dart
static Future spawn<T>(void entryPoint(T message), T message) async
```
I don't quite get how to pass a sendPort, when I spawn it, as there is no argument for the sendPort in the `spawn` method. Could you show an example, please?
