### ISSUE TITLE
Flutter : Module 'flutter_isolate' not found

### ISSUE THREAD

**Issue by samiulllah** [rmawatson/flutter_isolate#116]
I've used flutter isolate android version is working in debugging and release but the iOS version is only working in debugging for release it throws an error i.e. /ios/Runner/GeneratedPluginRegistrant.m:42:9: Module 'flutter_isolate' not found.

**Comment by nmfisher** [comment]
@samiulllah does this happen with the example app? Usually when I see that error it's due to broken XCode/CocoaPods project files.

**Comment by nmfisher** [comment]
Closing as no response received. Please reopen if this persists.
