### ISSUE TITLE
Flutter Release Android Build: library 'package:flutter_isolate/flutter_isolate.dart' not found.

### ISSUE THREAD

**Issue by mterenzi** [rmawatson/flutter_isolate#117]
I just upgraded my flutter SDK from version 3.0.5 to 3.3.0 this morning and now I am unable to call isolates when building in release mode for Android. This behavior does not occur in debug builds. I have not tested on iOS. 

Error:
> Launching lib\main.dart on SM P610 in release mode...
Building with Flutter multidex support enabled.
√  Built build\app\outputs\flutter-apk\app-release.apk (20.7MB).
E/flutter (12471): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library flutter_isolate/flutter_isolate.dart' not found.
E/flutter (12471): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (12471): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter (12471): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (12471): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
Application finished.
Exited (sigterm)
>

Any advice on how to fix the binding would be appreciated.

Flutter Doctor:
>[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.3.0 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
>
>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at C:\Android_SDK
    • Platform android-31, build-tools 29.0.2
    • Java binary at: C:\Program Files\Java\jdk-11.0.12\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
    • All Android licenses accepted.
>
>[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
>
>[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0
>
>[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
>
>[√] VS Code, 64-bit edition (version 1.70.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.29.0
>
>[√] Connected device (4 available)
    • SM P610 (mobile)  • R52T508QFSP • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 104.0.1293.70
>
>[√] HTTP Host Availability
    • All required HTTP hosts are available
>
>! Doctor found issues in 1 category.
>

**Comment by Thesmader** [comment]
I also faced this same issue today. I am using [isolate_handler](https://pub.dev/packages/isolate_handler) which depends on this plugin. The isolate creation fails in release mode:

```
E/flutter ( 6127): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:flutter_isolate/flutter_isolate.dart' not found.
E/flutter ( 6127): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter ( 6127): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter ( 6127): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter ( 6127): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
```

**Comment by mterenzi** [comment]
I am also using that package due to its ability to make platform dependent calls. Are you also experiencing this on iOS by any chance?

**Comment by mterenzi** [comment]
After doing some more research, it seems to be an issue with Flutter's obfuscation pass during a release build. I'm not 100% sure on that, but that's my best working theory. Not sure how to fix that, though.

**Comment by Coder-Manuel** [comment]
> I also faced this same issue today. I am using [isolate_handler](https://pub.dev/packages/isolate_handler) which depends on this plugin. The isolate creation fails in release mode:
> 
> ```
> E/flutter ( 6127): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:flutter_isolate/flutter_isolate.dart' not found.
> E/flutter ( 6127): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
> E/flutter ( 6127): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
> E/flutter ( 6127): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
> E/flutter ( 6127): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
> ```

I also got the same challenge with the builds from my pipeline which use the latest flutter version.
A quick fix for me was to downgrade to flutter version 3.0.5.

**Comment by srmanc** [comment]
This PR should fix it. https://github.com/rmawatson/flutter_isolate/pull/118

**Comment by mterenzi** [comment]
PR fixed the issue for me. Will close issue when officially merged.

**Comment by mterenzi** [comment]
Pull request has been merged. Waiting on pub version update and example documentation update to refrence the new pragma decorator requirement.

**Comment by mterenzi** [comment]
Pub version released. Closing issue,
