### ISSUE TITLE
Is this plugin still actively supported?

### ISSUE THREAD

**Issue by srmanc** [rmawatson/flutter_isolate#119]
Title says it all - is this plugin still actively supported?

There are at least two PRs which need to me merged and unbreak a lot of functionality (and even unbreak basic behaviour with production builds with flutter 3.x).

Especially:
https://github.com/rmawatson/flutter_isolate/pull/93
https://github.com/rmawatson/flutter_isolate/pull/118

@rmawatson Please take a look and merge. Or please let us know you will not support the plugin any longer so that the community may take over.

**Comment by nmfisher** [comment]
Yes I have taken over maintenance but I can’t respond to issues straight away. I’ll review those new PRs soon.

**Comment by srmanc** [comment]
@nmfisher Thank you for the clarification and many thanks for taking over.

**Comment by rlueders** [comment]
I dont think anyone is look for a straightaway response, but  one of those issues is almost a year old. This package is basically useless with all of these bugs.   I just opened #120 yesterday which causes the app to crash hard on a modern IOS device when when any isolate is killed.  I dont know how anyone can use a package in this state.
