### ISSUE TITLE
Calling FlutterIsolate.kill() crashes an iphone 12 pro max in release mode

### ISSUE THREAD

**Issue by rlueders** [rmawatson/flutter_isolate#120]
Calling FlutterIsolate.kill()or FlutterIsolate.killAll() crashes the entire app on a iphone 12 pro max in release mode (but works fine in debug or profile). No errors in the log because it only happens in release. I have also tested on an iphone 7 and kill/killAll works fine in release (as well as debug and profile). Both iphones are running ios 15.7. I don't see the crash on any of my android devices (pixel 2, 3, 4 5a, or 6a).

**Comment by nmfisher** [comment]
@rlueders does this happen with the example app?

**Comment by rlueders** [comment]
Im not sure about the example app, but I just tested with [PR93](https://github.com/rmawatson/flutter_isolate/pull/93/commits) and it appears to have fixed this behavior.  So, this issue can probably be closed with that PR. Thanks!
