### ISSUE TITLE
Can I use get_it dependency injection with flutter_isolate?

### ISSUE THREAD

**Issue by Dev11-ultroNeous** [rmawatson/flutter_isolate#133]
Hi 
How can I use get_it dependency injection into FlutterIsolate.spawn?
**Error:** 
"SyncCubit exception 'package:get_it/get_it_impl.dart': Failed assertion: line 372 pos 7: 'instanceFactory != null': Object/factory with  type ProjectListUseCase is not registered inside GetIt.
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
 Did you forget to register it?)"
**Example :**

  static final ProjectListUseCase _projectListUseCase = di.getIt<ProjectListUseCase>();
   Future<void> syncProjectData() async {
      final receivePort = ReceivePort();
      final isolate = await FlutterIsolate.spawn(
          pageFetch, receivePort.sendPort);
      receivePort.listen((dynamic response) {
        if (response is String) {
           Log.d("Api Response   $response");
        } else if (response is Error) {
        }
        isolate.kill();
      });
  }
  @pragma('vm:entry-point')
 static void pageFetch(SendPort sendPort) async {
    try {
      int limit = 10;
      int page = 0;
      Map<String, dynamic> map =
          getRequestMapDataForPopupPagination(page, limit, false, "");
      List<Popupdata> items =
          await _projectListUseCase.getPopupDataList(page, limit, map);
      Log.d("SyncCubit pageFetch ${items.length}");
      sendPort.send(items);
    } catch (e) {
      Log.d("SyncCubit exception ${e}");
      sendPort.send("SyncCubit exception ${e}");
    }
  }

**Comment by nmfisher** [comment]
I don't know about that package specifically, but anything static final in one isolate is separate from the same in another isolate. If you register an instance against your DI container in one isolate, it won't be available in the other.

Try sending the instance via the SendPort.

**Comment by Dev11-ultroNeous** [comment]
Thank you @nmfisher
