### ISSUE TITLE
Is it possible to work under sleep mode?

### ISSUE THREAD

**Issue by chunhunghan** [rmawatson/flutter_isolate#14]
Thank you for your amazing work.
I have tested with the following code in real device, and I found when Android enter sleep mode for a while. The Timer stop to send notification.
Is it possible to work under sleep mode, or my code just have bugs. 
Thanks.

	import 'package:flutter_isolate/flutter_isolate.dart';
	import 'dart:async';
	import 'package:flutter/material.dart';
	import 'dart:isolate';

	void main() => runApp(new MyApp());

	class MyApp extends StatelessWidget {
	  @override
	  Widget build(BuildContext context) {
		return new MaterialApp(
		  title: 'Flutter Isolate Demo',
		  theme: new ThemeData(
			primarySwatch: Colors.blue,
		  ),
		  home: new MyHomePage(title: 'Flutter Isolates'),
		);
	  }
	}

	class MyHomePage extends StatefulWidget {
	  MyHomePage({Key key, this.title}) : super(key: key);
	  final String title;

	  @override
	  _MyHomePageState createState() => new _MyHomePageState();
	}

	class _MyHomePageState extends State<MyHomePage> {
	  FlutterIsolate _isolate;
	  bool _running = false;
	  static int _counter = 0;
	  String notification = "";
	  ReceivePort _receivePort;

	  void _start() async {
		_running = true;
		_receivePort = ReceivePort();
		_isolate = await FlutterIsolate.spawn(_checkTimer, _receivePort.sendPort);
		_receivePort.listen(_handleMessage, onDone:() {
		  print("done!");
		});
	  }

	  static void _checkTimer(SendPort sendPort) async {
		Timer.periodic(new Duration(seconds: 60), (Timer t) {
		  _counter++;
		  String msg = 'notification ' + _counter.toString();
		  print('SEND: ' + msg);
		  sendPort.send(msg);
		});
	  }

	  void _handleMessage(dynamic data) {
		print('RECEIVED: ' + data);
		setState(() {
		  notification = data;
		});
	  }

	  void _stop() {
		if (_isolate != null) {
		  setState(() {
			_running = false;
			notification = '';
		  });
		  _receivePort.close();
		  //_isolate.kill(priority: Isolate.immediate);
		  _isolate.kill();
		  _isolate = null;
		}
	  }

	  @override
	  Widget build(BuildContext context) {
		return new Scaffold(
		  appBar: new AppBar(
			title: new Text(widget.title),
		  ),
		  body: new Center(
			child: new Column(
			  mainAxisAlignment: MainAxisAlignment.center,
			  children: <Widget>[
				new Text(
				  notification,
				),
			  ],
			),
		  ),
		  floatingActionButton: new FloatingActionButton(
			onPressed: _running ? _stop : _start,
			tooltip: _running ? 'Timer stop' : 'Timer start',
			child: _running ? new Icon(Icons.stop) : new Icon(Icons.play_arrow),
		  ),
		);
	  }
	}

**Comment by chunhunghan** [comment]
sorry my bad. Change Timer counter to local variable. Thanks.

**Comment by MichealReed** [comment]
@chunhunghan could you please elaborate on your fix? Is the timer required? I am running background processes with bluetooth and my process tops after about 15 minutes of the device going to sleep.

**Comment by chunhunghan** [comment]
variable counter in function _checkTimer have to use local variable.

	static void _checkTimer(SendPort sendPort) async {
		int counter = 0;
		Timer.periodic(new Duration(seconds: 60), (Timer t) {
		  counter++;
		  String msg = 'notification ' + counter.toString();
		  print('SEND: ' + msg);
		  //sendPort.send(msg);
		  sendPort.send(counter);
		});
	  }

There is also a package https://pub.dev/packages/screen can keep screen on 

    Screen.keepOn(true);
