### ISSUE TITLE
Unable to pass List<Uint8List>

### ISSUE THREAD

**Issue by tnghieu** [rmawatson/flutter_isolate#142]
```
@pragma('vm:entry-point')
void startProcessingImagesInBackground(List<List<Uint8List>> imageFiles) async {
  await FlutterIsolate.spawn(separateBatches, imageFiles);
}

@pragma('vm:entry-point')
void separateBatches(List<List<Uint8List>> imageFiles) async {
  for (List<Uint8List> images in imageFiles) {
    await flutterCompute(processBatch, images);
  }
}

@pragma('vm:entry-point')
Future<List<ResultObjectDetection>> processBatch(List<Uint8List> images) async {
  List<ResultObjectDetection> resultsForThisBatch = [];
  for (Uint8List image in images) {
    List<ResultObjectDetection> results =
        await objectDetectionModel.getImagePrediction(
      image,
      minimumScore: 0.75,
      preProcessingMethod: pt_model.PreProcessingMethod.native,
    );
    resultsForThisBatch.addAll(results);
  }
  return resultsForThisBatch;
}
```

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: is a Type: Uint8List

Unable to process this data with flutter_isolate. Can I only pass primitive types?

**Comment by nmfisher** [comment]
Confirm I can reproduce on iOS simulator.

**Comment by nmfisher** [comment]
@tnghieu I doubt this is functioning correctly so I will file an issue against the dart-lang/sdk repository. If you need an immediate workaround, I suggest you pass things around as `List<List<int>>` rather than `List<Uint8List>`

**Comment by nmfisher** [comment]
Fix has been merged into the dartlang SDK, so wait for that to appear upstream and bump your SDK version number.

In the meantime, try sending as List<List<int>> or wrapping with `TransferableTypedData` (suggested by Dart maintainers, I haven't actually tried that myself).
