### ISSUE TITLE
Support uuid 4.x

### ISSUE THREAD

**Issue by kuhnroyal** [rmawatson/flutter_isolate#143]
Library needs to be updated to support uuid package 4.x version.

**Comment by nmfisher** [comment]
Thanks @kuhnroyal - are you able to submit a PR for this?

**Comment by nmfisher** [comment]
Thanks!

**Comment by kuhnroyal** [comment]
Your welcome, would love a release with this change :)

**Comment by nmfisher** [comment]
@kuhnroyal `2.0.5-pre` should be available on pub.dev soon.
