### ISSUE TITLE
Cannot run the example，

### ISSUE THREAD

**Issue by lwlizhe** [rmawatson/flutter_isolate#23]
**error msg:**
---
Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before runApp() has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized() first.
If you're running a test, you can call the TestWidgetsFlutterBinding.ensureInitialized() as the first line in your test's main() method to initialize the binding.
………………

but it doesn't work ……

**my code:**
---
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final isolate = await FlutterIsolate.spawn(isolate1, "hello");
  Timer(Duration(seconds: 5), () {
    print("Pausing Isolate 1");
    isolate.pause();
  });
  Timer(Duration(seconds: 10), () {
    print("Resuming Isolate 1");
    isolate.resume();
  });
  Timer(Duration(seconds: 20), () {
    print("Killing Isolate 1");
    isolate.kill();
  });

  runApp(MyApp());
}
```
**flutter doctor：**
---
> [√] Flutter (Channel master, v1.10.6-pre.39, on Microsoft Windows [Version 10.0.17763.107], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[!] VS Code, 64-bit edition (version 1.32.3)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (2 available)

Where am I wrong?

**Comment by lwlizhe** [comment]
This problem is solved……

This is my flutter configuration problem

**Comment by lwlizhe** [comment]
Cannot run on the latest version.

but it can run on version 1.5.4……

**Comment by lwlizhe** [comment]
switch to the stable channel can solve this ……

**Comment by LavaJelly** [comment]
i can't run the example too! i'm on 1.9.1 + hotfix.5 and stable channel... 

![image](https://user-images.githubusercontent.com/57488456/68388839-4d061380-0140-11ea-9bb6-32ac36f9b3da.png)
i'm kinda new to flutter so any help is apreciated.

**Comment by lwlizhe** [comment]
> i can't run the example too! i'm on 1.9.1 + hotfix.5 and stable channel...
> 
> ![image](https://user-images.githubusercontent.com/57488456/68388839-4d061380-0140-11ea-9bb6-32ac36f9b3da.png)
> i'm kinda new to flutter so any help is apreciated.

maybe you need this:
https://pub.dev/packages/flutter_startup

**Comment by LavaJelly** [comment]
Thanks for the fast answer and Sorry for no post anything else... here are my pubspec 
![image](https://user-images.githubusercontent.com/57488456/68389467-ca7e5380-0141-11ea-8c41-4e518fe51de5.png)

and this is where the error come from...
![image](https://user-images.githubusercontent.com/57488456/68389562-03b6c380-0142-11ea-9270-55cef668f1f5.png)

**Comment by lwlizhe** [comment]
> Thanks for the fast answer and Sorry for no post anything else... here are my pubspec
> ![image](https://user-images.githubusercontent.com/57488456/68389467-ca7e5380-0141-11ea-8c41-4e518fe51de5.png)
> 
> and this is where the error come from...
> ![image](https://user-images.githubusercontent.com/57488456/68389562-03b6c380-0142-11ea-9270-55cef668f1f5.png)a

Maybe these issue can help you，it should not  be the problem of flutter_isolate.

https://github.com/flutter/flutter/issues/10912#issuecomment-536569481
https://github.com/flutter/flutter/issues/10912
https://github.com/flutter/flutter/issues/12264

**Comment by LavaJelly** [comment]
i've tried all in your asnwer... even now i started a new flutter project, only with: 
flutter_startup: ^0.0.2 
flutter_isolate: ^1.0.0+9
and the example in the flutter_isolate page. i even made another emulator and i still got the same error... 
i'm going to cry :'(

**Comment by lwlizhe** [comment]
> i've tried all in your asnwer... even now i started a new flutter project, only with:
> flutter_startup: ^0.0.2
> flutter_isolate: ^1.0.0+9
> and the example in the flutter_isolate page. i even made another emulator and i still got the same error...
> i'm going to cry :'(

um,I don't know where is wrong……… :P

but you can remove flutter_startup from your code ,its not the part of flutter_isolate…… read the document then try to write a new demo.

The correct usage of flutter_isolate  is like this:
`FlutterIsolate.spawn(your isolate method,tag)`

**Comment by LavaJelly** [comment]
WHAT?! is not dependant on flutter_startup?! ; ^; thx a lot for telling me that!

**Comment by nmfisher** [comment]
Given some months have passed since this comment and the example app has since been updated, I will close for now - if you experience any problems please open a new issue.
