### ISSUE TITLE
Trouble getting the example app to work 

### ISSUE THREAD

**Issue by Drkstr** [rmawatson/flutter_isolate#34]
I was having some trouble getting the plugin to work and taught id try to clone the example app and try to get that working. But I can't get the example app to work either.  😢 

I have cloned the repo and after running `flutter pub get` I get the following error on the IDE. 

- Target URI doesn't exist "package:flutter_startup/flutter_startup.dart"
- The getter 'platformVersion' isn't defined for the class FlutterIsolate 
- The name 'PlatformException' isn't a type and cant be used in an on-catch clause 

The app also seems to be missing the StatefulWidget class on the MyApp widget.  (easily fixed) 

What am I missing here?

**Comment by shfkhalifa** [comment]
I am having the same issue.. anyone has figured out what is wrong?

**Comment by nmfisher** [comment]
Given some months have passed since this comment and the example app has since been updated, I will close for now - if you experience any problems please open a new issue.
