### ISSUE TITLE
Not clear how to get result from isolate

### ISSUE THREAD

**Issue by syonip** [rmawatson/flutter_isolate#35]
Hi,
Is there a way to get a result / communicate with the isolate in any way?
Is there a way to know that the operation has finished instead of just killing it with a timer?

Thanks.

**Comment by zkon** [comment]
Hi, I also can't see how the isolate can return data or communicate that the requested operation has completed. I'm trying to do some image processing in the isolate and need to know when that has completed, before another function can continue and use the processed image.

**Comment by elmissouri16** [comment]
@zkon I have a similar issue related to video processing  I'm stuck initialing the plugging to work with flutter_isolate
if it's possible to share the code to use it with plugin that uses method channel thank you

**Comment by nmfisher** [comment]
I have added some documentation about using SendPort/ReceivePort to communicate between isolates, please see the current README.
