### ISSUE TITLE
Can't run the example - MissingPluginException

### ISSUE THREAD

**Issue by LeXuanKhanh** [rmawatson/flutter_isolate#36]
I try to run a simple example code:
```
void isolate1(String arg) async  {
  Timer.periodic(Duration(seconds:1),(timer)=>print("Timer Running From Isolate 1"));
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final isolate = await FlutterIsolate.spawn(isolate1, "hello");
  runApp(MyApp());
}
```

But it got error: 
```
E/flutter (16452): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method spawn_isolate on channel com.rmawatson.flutterisolate/control)
E/flutter (16452): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (16452): <asynchronous suspension>
E/flutter (16452): #1      FlutterIsolate.spawn (package:flutter_isolate/flutter_isolate.dart:45:14)
E/flutter (16452): #2      main (package:flutter_isolate_demo/main.dart:14:40)
E/flutter (16452): #3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (16452): #4      main (package:flutter_isolate_demo/main.dart:12:10)
E/flutter (16452): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (16452): #6      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (16452): #7      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (16452): #8      _runZoned (dart:async/zone.dart:1518:10)
E/flutter (16452): #9      runZoned (dart:async/zone.dart:1502:12)
E/flutter (16452): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (16452): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (16452): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (16452): 
```
Flutter doctor:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.42.1)
[√] Connected device (1 available)
• No issues found!
```
I have looked at issue #25 , #12  but seem like it different from those because i haven't used this with any other plugins

**Comment by henoktadesse** [comment]
Any new updates on this? facing the same issue

**Comment by ryanheise** [comment]
@LeXuanKhanh and @henoktadesse , can you copy and paste your pubspec.yaml dependencies and flutter doctor? I see in @LeXuanKhanh 's case that it's happening on Android. @henoktadesse , is the issue on Android for you, too or iOS, or both?

**Comment by EKALEB** [comment]
the same issue on Android, using flutter_isolate: 1.0.0+14 in pubspec.yaml

**Comment by ryanheise** [comment]
@EKALEB can you share your pubspec.yaml dependencies in full? Or are you saying that flutter_isolate is the only plugin that your app uses?

**Comment by cccRaim** [comment]
maybe try to reinstall the app.

**Comment by lyio** [comment]
@ryanheise I think this is the example here in the repository.

The code for iOS in the `AppDelegate` in the readme and in the example dow not look like it will run. The class `FlutterIsolatePlugin` does not have a property `isolatePluginRegistrantClassName` and XCode will refuse to compile this.

At least I don't find it.

Maybe the example or the documentation are outdated, I don't know.

**Comment by nmfisher** [comment]
@lyio It's possible the iOS instructions in the README require updating, let me check.

**Comment by lyio** [comment]
No, it's the other way around...

The docs are more recent than the released version. They align with the 2.1.0 pre-release.

My bad.

Also, I tried to spawn an isolate from the flutter_downloader, which itself only has a headless Flutter engine, and kept getting the MissingPluginException because ofc the flutter_isolate had not been registered there.

**Comment by nmfisher** [comment]
OK, given the amount of time that's elapsed since the original issue and no comment from the original poster, I'll close this if no further response received in the next 7 days.
