### ISSUE TITLE
why can't send and receive objects with this plugin isolate while I can do that in a normal isolate

### ISSUE THREAD

**Issue by moda20** [rmawatson/flutter_isolate#37]
I am trying to use plugins in myna isolate and it didn't work, so I transitioned to this plugin to create isolates with but once running my old code after modifying it to use this plugin I got the error `Illegal argument in isolate message : (object is a regular Dart Instance)`. 

I have been using the following code and not have a problem with it :

```dart
messageToBeSent = new CrossIsolatesMessage(
        sender: messageToBeSent.sender==null?port.sendPort:messageToBeSent.sender,
        message: messageToBeSent.message,
        command: messageToBeSent.command);

    newIsolateSendPort.send(messageToBeSent);
```

CRossIsolateMessage is an object and I am being able to send it via the isolate and I do receive that exact object on the other hand and I can send back more complex objects through the ports.

is this something related to the nativeIsolate thing?

**Comment by govanyjj** [comment]
@rmawatson @moda20  I've also encountered this problem, are there any recent developments or related solutions?

**Comment by nmfisher** [comment]
Per the Dart documentation:

`In the special circumstances when two isolates share the same code and are running in the same process (e.g. isolates created via Isolate.spawn), it is also possible to send object instances (which would be copied in the process). This is currently only supported by the Dart Native platform.`

flutter_isolate doesn't invoke Isolate.spawn directly; isolates are spawned by creating a new FlutterEngine (which, presumably doesn't satisfy these conditions - it may happen off-thread somewhere). 

This is unlikely to change in the near future, but there is an issue to investigate switching from this approach to a plain Dart-isolate approach (https://github.com/rmawatson/flutter_isolate/issues/15).

I've updated the README with details of communicating between isolates with SendPort/ReceivePort, so I will close this for now.
If you're interested in progress, please track the other issue.
