### ISSUE TITLE
Crash on iOS when use google_sign_in plugin

### ISSUE THREAD

**Issue by miphik** [rmawatson/flutter_isolate#50]
Hi,
First, thank you for your work!
I have a crash on iOS when using your plugin together with the [google_sign_in](https://pub.dev/packages/google_sign_in) plugin.
The problem is on the next line: [FLTGoogleSignInPlugin.m#L243](https://github.com/flutter/plugins/blob/0fab93dc91cc9085da0b9e5ff034c28b5541c9fb/packages/google_sign_in/google_sign_in/ios/Classes/FLTGoogleSignInPlugin.m#L243).
When I call `FlutterIsolate.spawn` before trying to login using google and try to login , my app crashes on iOS because of `_accountRequest` is nil.
If I don't call `FlutterIsolate.spawn` login works perfectly.
Really appreciate any help.

**Comment by suztomo** [comment]
@miphik I have similar problem. When I use flutter_isolate, then google_sign_in does not work. I found similar problem in Firestore, where Firestore library is not handling MethodChannel when there are multiple isolates (https://github.com/FirebaseExtended/flutterfire/issues/4108)

Which do you think the problem is in google_sign_in or flutter_isolate?

**Comment by miphik** [comment]
I guess the problem is `google_sign_in`, I saw the same error with another plugin, but I can't be 100% sure, I don't have any experience with object-c.
for me, this issue was fixed by migrating from `flutter_isolate` to flutter native isolate

**Comment by nmfisher** [comment]
@miphik From what I gather, you may need to register a custom plugin registrant to do this. This capability is now available on master, can you try this and advise if this fixes your issue?

**Comment by miphik** [comment]
Hey @nmfisher 
thank you for the reply
cannot check it, Im using native isolates now
will close this issue.
