### ISSUE TITLE
MissingPluginException using flutter_blue

### ISSUE THREAD

**Issue by medleykupps** [rmawatson/flutter_isolate#53]
I'm receiving the following error message when scanning for Bluetooth devices in a background isolate using flutter_blue.

`MissingPluginException(No implementation found for method isAvailable on channel plugins.pauldemarco.com/flutter_blue/methods)`

This works fine when I run it in the main Isolate, hence, why I'm posting it here. I'm running this on an Android device (Pixel 3a). And, I had a very similar application running successfully on an iPhone recently. Unfortunately I'm no longer able to test this on an iPhone just at the moment, but, was hoping to get it running on Android.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.388], locale en-AU)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 4.0)
[✓] VS Code, 64-bit edition (version 1.47.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Using:

```
flutter_isolate: 1.0.0+14
flutter_blue: 0.7.2
```

And, I'm trying a simple scan and log:

```
FlutterBlue.instance.scan(
    timeout: Duration(milliseconds: 5000))
    .listen(
        (scanResults) {
        FLog.info(text: 'Found device ${scanResults.device.name}', dataLogType: DataLogType.DEVICE.toString());
    });
```

Just wondering if there is a solution or work around for this?

**Comment by Ozzy340** [comment]
I am also hitting this problem - I am assuming this is a newer version of flutter that has created this problem.
It appears to be whenever trying to access the 'FlutterBlue.instance'

**Comment by nmfisher** [comment]
Thanks for the issue - this is a known issue that is being tracked, so I will close this in favour of https://github.com/rmawatson/flutter_isolate/issues/71.
