### ISSUE TITLE
How to send and receive data through isolate ports

### ISSUE THREAD

**Issue by MuhammedRefaat** [rmawatson/flutter_isolate#54]
Like regular Flutter isolate, I need to send data across different isolates (send data from the isolate to the isolate initiator), and I can't find a way to achieve that in this package:

```
// at the initiator side
ReceivePort receivePort =
        ReceivePort(); //port for isolate to receive messages.
receivePort.listen((data) {
        print('Receiving: ' + data + ', ');
    });

// at the isolator
sendPort.send("A");
```

**Comment by ryanheise** [comment]
You can use [IsolateNameServer](https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html) to share the send port between flutter_isolate and another isolate.

**Comment by RalphMarvin** [comment]
> You can use [IsolateNameServer](https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html) to share the send port between flutter_isolate and another isolate.

How's that gonna work ? Can anyone share a code sample ?

**Comment by suztomo** [comment]
@RalphMarvin Here you are

```
  print('spawning isolate');
  final flutterIsolate =
      await FlutterIsolate.spawn(_downloadingIsolate, destinationPath)
          as FlutterIsolate;

  final receivePort = ReceivePort();
  final sendPort = receivePort.sendPort;
  IsolateNameServer.registerPortWithName(sendPort, 'main');

  receivePort.listen((dynamic message) {
    if (message == 'done') {
      print('Killing the Isolate');
      flutterIsolate.kill();
    }
  });
```

```
Future<void> _downloadingIsolate() async{
...
    final port = IsolateNameServer.lookupPortByName('main');
    if (port != null) {
      port.send('done');
    } else {
      print('port is null');
    }
```

**Comment by mahdidham** [comment]
> @RalphMarvin Here you are
> 
> ```
>   print('spawning isolate');
>   final flutterIsolate =
>       await FlutterIsolate.spawn(_downloadingIsolate, destinationPath)
>           as FlutterIsolate;
> 
>   final receivePort = ReceivePort();
>   final sendPort = receivePort.sendPort;
>   IsolateNameServer.registerPortWithName(sendPort, 'main');
> 
>   receivePort.listen((dynamic message) {
>     if (message == 'done') {
>       print('Killing the Isolate');
>       flutterIsolate.kill();
>     }
>   });
> ```
> 
> ```
> Future<void> _downloadingIsolate() async{
> ...
>     final port = IsolateNameServer.lookupPortByName('main');
>     if (port != null) {
>       port.send('done');
>     } else {
>       print('port is null');
>     }
> ```

after i test this, honestly I am only able to send string or null instead of object

**Comment by thize** [comment]
@mahdidham maybe you can send a json string and convert it later

**Comment by nmfisher** [comment]
I have updated the README to reflect how to communicate via SendPort/ReceivePort.
