### ISSUE TITLE
Can we encode using flutter_ffmpeg inside a flutter_isolate?

### ISSUE THREAD

**Issue by aytunch** [rmawatson/flutter_isolate#55]
Encoding with [flutter_ffmpeg](https://github.com/tanersener/flutter-ffmpeg) takes too much time and resources and generates Jank in the UI. So it would be very nice if we could run it in a background thread. Can we do it with the help of your library? If yes, is there a way to get progress callbacks from the thread? I want to show the user how much encoding is done. Normally flutter_ffmpeg gives this callback in its API.

Also, is there a straightforward way to allow this isolate to keep on working while the app is in the background?

**Comment by nmfisher** [comment]
@aytunch I don't see any reason why this can't be done. I have no idea what the flutter_ffmpeg API looks like, but presumably you could do something like this:
```
void ffmpegDecoder(Map<String,dynamic> args) {
var filename = args["filename"];
var sendPort = args["sendPort"];
flutter_ffmpeg_plugin.decode(filename, onUpdateProgress:(progress) {
sendPort.send("Here's a progress update : $progress");
});
}

void main() {
var port = ReceivePort();
var filename = "myfile.mpg";
port.listen((message) {
print("Decode status : $message");
});
FlutterIsolate.spawn(ffmpegDecoder, {"port":port.sendPort, "filename":filename});
}
```
Given this has been open for some months, I suggest you give it a try and if you experience any problems, please open a new issue and I will be happy to help.
