### ISSUE TITLE
Can I Send A Message To The Main Thread

### ISSUE THREAD

**Issue by RalphMarvin** [rmawatson/flutter_isolate#57]
I am running a process in my app on the `flutter_isolate` from this plugin and would like to a way to communicate with the main thread once the task am running in the isolate is completed. I want to know if thats possible with the plugin because it doesnt mention this in the docs.

**Comment by ryanheise** [comment]
You can use [IsolateNameServer](https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html) to communicate between isolates (it's not a feature of this plugin but rather a standard Dart/Flutter API.)

**Comment by RalphMarvin** [comment]
> You can use [IsolateNameServer](https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html) to communicate between isolates (it's not a feature of this plugin but rather a standard Dart/Flutter API.)

Okay thank You. Then am closing this issue now
