### ISSUE TITLE
very hard to use this thing, many many problem here .  

### ISSUE THREAD

**Issue by KyleLUO** [rmawatson/flutter_isolate#58]
/flutter ( 6851): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
E/flutter ( 6851): #0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:219:70)
E/flutter ( 6851): #1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:203:5)
E/flutter ( 6851): #2      FlutterIsolate.spawn.<anonymous closure>
package:flutter_isolate/flutter_isolate.dart:39
E/flutter ( 6851): #3      _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 6851): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6851): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6851): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 6851): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 6851): #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter ( 6851): #9      _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter ( 6851): #10     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter ( 6851): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by nmfisher** [comment]
You can only send primitives via a SendPort to communicate between isolates.

https://github.com/dart-lang/sdk/blob/7c148d029de32590a8d0d332bf807d25929f080e/sdk/lib/isolate/isolate.dart#L620

I've added some more documentation to the README to explain.
