### ISSUE TITLE
How does the main isolate get notified of flutter_isolate work completion?

### ISSUE THREAD

**Issue by acherkashyn** [rmawatson/flutter_isolate#6]
I think I'm missing something pretty obvious here, but how do I know that flutter_isolate has completed computation passed into the `spawn` method? Is there a callback to be notified, or a future to subscribe to?

**Comment by rmawatson** [comment]
pass in a SendPort as the argument like with a regular isolate and use this for notifying your main isolate.

**Comment by acherkashyn** [comment]
Thank you, that makes sense.

**Comment by zhanghuanchong** [comment]
@rmawatson Could you please add a sample code in the documentation for getting data from the isolate? #10 #11 were also asking this question. Thanks.

**Comment by zhanghuanchong** [comment]
I found a sample code here: https://stackoverflow.com/a/56349960/6622926
