### ISSUE TITLE
An Exeption occure

### ISSUE THREAD

**Issue by MuhammedJaseel** [rmawatson/flutter_isolate#62]
NoSuchMethodError: The method 'toRawHandle' was called on null.

**Comment by radomir9720** [comment]
Hi @MuhammedJaseel.
You just need to pass to first positional parameter of `spawn` method a `static` method or a top-level method.

Example of a `static` method:
```dart
abstract class MyClass {
    static Future<void> myStaticMethod(Map<String, dynamic> context) {
        // your implementation
    }
}
```

how to use:
```dart
iso.spawn<Map<String, dynamic>>(
      MyClass.myStaticMethod,
      name: 'iso',
    );
```

**Comment by pmagnuson** [comment]
I am having a similar issue to the with toRawHandle.  Do you have and example with flutter_notification as mentioned in the README?

**Comment by radomir9720** [comment]
Hi @pmagnuson. If you will show your code it will be easier to tell what is wrong. Also you can ask in [this telegram channel](https://t.me/rudart) your question. The channel is in russian, but you can ask on english.

**Comment by nmfisher** [comment]
@MuhammedJaseel @pmagnuson I have added some details to the README explaining how to invoke FlutterIsolate.spawn with static/top-level functions.

Let me know if you need further guidance, otherwise I will close in 7 days.
