### ISSUE TITLE
Flutter is deprecating BinaryMessages field

### ISSUE THREAD

**Issue by pschuegr** [rmawatson/flutter_isolate#63]
FYI, https://github.com/flutter/flutter/pull/73750 removes the BinaryMessages field used here: https://github.com/rmawatson/flutter_isolate/blob/master/lib/flutter_isolate.dart#L103

I'll submit a PR if I get a chance to put one together, but the change is to:

` window.onPlatformMessage = ServicesBinding.instance.defaultBinaryMessenger.handlePlatformMessage;`

**Comment by megamegax** [comment]
I can't build my app because of this error message:

../../.pub-cache/hosted/pub.dartlang.org/flutter_isolate-1.0.0+14/lib/flutter_isolate.dart:103:32: Error: Getter not found: 'BinaryMessages'.
    window.onPlatformMessage = BinaryMessages.handlePlatformMessage;

What should I use as a workaround if I want to use the latest versions of flutter?

**Comment by ryanheise** [comment]
@megamegax there is a pull request (#64 ) which you can test.

**Comment by ryanheise** [comment]
@megamegax this should be fixed in the latest commit to `master`. Can you try it?

**Comment by ryanheise** [comment]
I have heard no bug reports regarding this commit so I'll publish a new release.

**Comment by ryanheise** [comment]
This fix is now published in 1.0.0+15.
