### ISSUE TITLE
Example Does not work on windows desktop

### ISSUE THREAD

**Issue by syleishere** [rmawatson/flutter_isolate#67]
Building Windows application...
Debug service listening on ws://127.0.0.1:63522/4j_CDVGFGxA=/ws
Syncing files to device Windows...
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method spawn_isolate on channel com.rmawatson.flutterisolate/control)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method spawn_isolate on channel com.rmawatson.flutterisolate/control)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>

**Comment by nmfisher** [comment]
Yes this is currently not implemented - would make a good first issue if someone wants to contribute.

**Comment by nmfisher** [comment]
Closing in favour of https://github.com/rmawatson/flutter_isolate/issues/51.
