### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by juliansteenbakker** [rmawatson/flutter_isolate#68]
This plugin uses deprecated functions to spawn a Flutter view. This should be migrated to the newest version.
```dart
import io.flutter.view.FlutterMain;
import io.flutter.view.FlutterNativeView;
```

**Comment by ryanheise** [comment]
This is migrated to the newest version (see #42 ) but it conditionally will support the old APIs also by checking if the app is using the latest SDK or not. But yes the old APIs can be safely removed now, we don't need to support them anymore.

@rohansohonee Would you be interested in updating this?

**Comment by juliansteenbakker** [comment]
Since we are now supporting null-safety, a new version of flutter is required by flutter anyway. I can make a pull-request if you want.

**Comment by ryanheise** [comment]
Awesome! Yes, I'd be happy to merge if you were to submit a PR.
