### ISSUE TITLE
WANTED: New package maintainer

### ISSUE THREAD

**Issue by ryanheise** [rmawatson/flutter_isolate#70]
I have been maintaining flutter_isolate for a little over a year thanks to @rmawatson granting me access to do so. I had an interest in maintaining it because [audio_service](https://github.com/ryanheise/audio_service) used it internally. However, audio_service is moving away from its old isolate model and I will no longer have a reason to continue this maintenance.

If anyone is interested in adopting the project, I'm sure @rmawatson would be happy to let you do that as he did for me.

I am aware that @deakjahn relies on flutter_isolate for the [isolate_handler](https://pub.dev/packages/isolate_handler) package, and @nmfisher is doing some [interesting work](https://github.com/nmfisher/flutter_isolate_engine_group) to reimplement flutter_isolate using the new FlutterEngineGroup API described in [this comment](https://github.com/flutter/flutter/issues/13937#issuecomment-784571153). Are either of you interested in inheriting the role? In the latter case, it would allow you to upgrade to the FlutterEngineGroup API while keeping the flutter_isolate name.

**Comment by deakjahn** [comment]
I actually know nothing of the upcoming changes except for the few words written in that issue, that something new is coming up that will make it possible to start the required engine much more cheaply (but I haven't yet checked what changes this actually means). So, yes, I'm interested in the outcome but that could also be just to keep using a changed package if Nick will do the work. In other words, count me in if I'm required, but I don't necessarily want to butt in and get extra rights if all I'm supposed to do is to remain a dependent package.

**Comment by rmawatson** [comment]
Happy to pass it on @deakjahn if your willing, and your new solution is the way forward.

**Comment by deakjahn** [comment]
Considering that, according to the original thread, the new API is already in Flutter 2.0, @nmfisher, will you check this out?

**Comment by nmfisher** [comment]
Hi @rmawatson  @ryanheise @deakjahn - yes I am happy to take this over, I'm fairly familiar with the existing flutter_isolate internals so it makes sense for me to act as maintainer + integrate the forthcoming work on FlutterEngineGroup.

**Comment by ryanheise** [comment]
@rmawatson It looks like I don't have access to the menu for adding collaborators so you may need to do it. There is also the matter of adding rights for publishing to pub.dev - I don't recall how we did that last time but there are two options:

1. Become a verified publisher and assign rights through the web UI: https://dart.dev/tools/pub/publishing#create-verified-publisher
2. Without becoming verified: https://dart.dev/tools/pub/cmd/pub-uploader

**Comment by rmawatson** [comment]
Hi Ryan, I've added Nick to the git hub repository. Your seconds link looks about right, I remember doing it in the terminal. I don't have the flutter tools installed are you able to take care of this?

**Comment by ryanheise** [comment]
@nmfisher I've just sent a pub uploader invitation to the email address appearing in your git logs.

**Comment by nmfisher** [comment]
Thanks both @rmawatson and @ryanheise - I've accepted all those invitations so I'll close this issue and reach out privately if anything is needed.
