### ISSUE TITLE
Can work in background forever? 

### ISSUE THREAD

**Issue by meridorkobi** [rmawatson/flutter_isolate#76]
great plugin!
I have to communicate to Bluetooth low energy device while my app in foreground or background. 
I need to catch special message.
Can I do it with the great plugin ?

**Comment by nmfisher** [comment]
In theory, flutter_isolate can communicate with Bluetooth while the app is in the foreground. 

However, there is some incompatibility between flutter_blue and flutter_isolate. This means you won’t be able to use that particular plugin for Bluetooth, so you’d have to find another plugin that’s compatible or do a lot of heavy lifting yourself via platform channels.

As it stands, you also won’t be able to use flutter_isolate in the background. I’ll investigate whether or not this is possible but it won’t be a priority at this point in time.

**Comment by meridorkobi** [comment]
Thanks,
In my test I wrote to MongoDB atlas from the isolate . Its working correctly while app in foreground and stopped after short time after moving to background.
a. Is it possible that isolate was stooped because the MongoDB activity?
b. Do you have recommendation for other Bluetooth low energy Plugin?
c. What is the advantage using isolate with  periodic timer inside than periodic timer?
Thanks Kobi

**Comment by nmfisher** [comment]
a. Is it possible your calls to MongoDB threw an exception? Otherwise, I would expect the isolate to finish execution (or, if you're looping, just continue processing).

b. I can't make any recommendations around Bluetooth sorry, not my area.

c. I don't understand the question

**Comment by meridorkobi** [comment]
I removed the isolate and and the timer and integrate the bluetooth and mongo to the blue lister and it's working great
