### ISSUE TITLE
Unable to communicate Map<String, String>

### ISSUE THREAD

**Issue by abhinavsingh** [rmawatson/flutter_isolate#77]
Hi,

Thank you for this excellent plugin.  We are evaluating it for our next project.  All seems to work fine, except when we try to use `libphonenumber`.   `libphonenumber` parse method returns a `Map<String, dynamic>`, frankly it's just a `Map<String, String>`.  However, communicating the result of `parse` over port results in `Illegal argument in isolate message : (object is a regular Dart Instance)`.

Below are a few lines of log we did for debugging purposes, see explanation below:

```
2021-05-29 20:29:35.140865+0530 Runner[846:131499] flutter: {national: 099999 99999, national_number: 9999999999, e164: +919999999999, type: mobile, international: +91 99999 99999, country_code: 91}
2021-05-29 20:29:35.140888+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.140902+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.140915+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.140932+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.140944+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.140955+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.141024+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.141176+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.141256+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.141501+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.141678+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.141766+0530 Runner[846:131499] flutter: String
2021-05-29 20:29:35.142282+0530 Runner[846:131499] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
#0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:235:70)
#1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:219:5)
```

1. 1st line simply prints the result returned by `libphonenumber`
2. Next, to double confirm, we printed `runtimeType` for each key and value.  They are all strings.
3. But still when we send this over port, an exception is raised.

We are unable to track it down to an exact reason.  We have also referred to documentation here https://github.com/dart-lang/sdk/blob/7c148d029de32590a8d0d332bf807d25929f080e/sdk/lib/isolate/isolate.dart#L620.

Any pointers to why exactly does this specific use case fails will be super helpful.  Thank you!!!

**Comment by nmfisher** [comment]
That's odd behaviour. Can you replicate this with a plain ReceivePort/SendPort, independently of flutter_isolate?

```
var myMap = {"key":"value"};
var foo = ReceivePort();
foo.listen((message) {print(message);});
foo.sendPort.send(myMap);
foo.sendPort.send(myMap.cast<String,String>());
var phoneNumbers = libphonenumber.parse(data);
foo.sendPort.send(phoneNumbers);
```

**Comment by abhinavsingh** [comment]
@nmfisher Usage of external plugin is the primary reason we started evaluating `flutter_isolate`.  With plain dart `isolate` we were unable to get our plugin dependent isolates working.

Having said that, I still want to do a explicit case, as you demonstrated, to see if that helps.  Please give me a day or so, I'll come back with my findings _(unfortunately away from Laptop for a day at-least)_.

Thank you!!!

**Comment by nmfisher** [comment]
Yes that’s just a test to make sure you’re passing things around correctly, I’m not suggesting replacing flutter_isolate with a Dart isolate.

What you posted should work, so there’s probably an error in your code somewhere.

**Comment by abhinavsingh** [comment]
> That's odd behaviour. Can you replicate this with a plain ReceivePort/SendPort, independently of flutter_isolate?
> 
> ```
> var myMap = {"key":"value"};
> var foo = ReceivePort();
> foo.listen((message) {print(message);});
> foo.sendPort.send(myMap);
> foo.sendPort.send(myMap.cast<String,String>());
> var phoneNumbers = libphonenumber.parse(data);
> foo.sendPort.send(phoneNumbers);
> ```

Just got back to it today and gave it a try.  Looks like that cast of map itself is unable to reach the other side.

```
2021-06-01 12:52:11.437267+0530 Runner[3539:1280369] flutter: {key: value}
2021-06-01 12:52:11.437504+0530 Runner[3539:1280479] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
#0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:235:70)
```

- 1st line is response as seen by receiver for `.send(myMap)` 
- 2nd one `.send(myMap.cast<String,String>())` fails

Can it be related to plugin registry? Currently we haven't customized that and let all plugins in the environment load for the isolated.

**Comment by abhinavsingh** [comment]
For reference code at my end:

```
  var myMap = {"key": "value"};
  port.send(myMap);
  port.send(myMap.cast<String, String>());
  var parsedNumber = await _libPhoneNumber.parse("+918948207807");
  port.send(parsedNumber);
```

**Comment by abhinavsingh** [comment]
For reference code at my end:

```
  var myMap = {"key": "value"};
  port.send(myMap);
  port.send(myMap.cast<String, String>());
  var parsedNumber = await _libPhoneNumber.parse("+919999999999");
  port.send(parsedNumber);
```

**Comment by abhinavsingh** [comment]
Update:  Amazingly this stupidity works out for now.

```
  var parsedNumber = await _libPhoneNumber.parse("+919999999999");
  var parsedMap = {};
  parsedNumber.forEach((key, value) {
    parsedMap[key] = value;
  });
  port.send(parsedMap);
```

Note that we are also using `contact_service` and we use it's `.toMap()` function to serialize over the port and it just works fine.  There is something mysterious about `.parse` here which I am unable to decipher.

Let me know if any further information is required to nail this down.

**Comment by nmfisher** [comment]
This has nothing to do with the plugin registry (or even Flutter). What version of Dart are you running? 

Can you also confirm you’re not using any package that is adding extensions to Map?

**Comment by abhinavsingh** [comment]
> This has nothing to do with the plugin registry (or even Flutter). What version of Dart are you running? Can you also confirm you’re not using any package that is adding extensions to Map?
> […](#)
> On 1 Jun 2021, at 4:39 PM, Abhinav Singh ***@***.***> wrote: ﻿ Update: Amazingly this stupidity works out for now. var parsedNumber = await _libPhoneNumber.parse("+919999999999"); var parsedMap = {}; parsedNumber.forEach((key, value) { parsedMap[key] = value; }); port.send(parsedMap); Note that we are also using contact_service and we use it's .toMap() function to serialize over the port and it just works fine. There is something mysterious about .parse here which I am unable to decipher. Let me know if any further information is required to nail this down. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I meant the same, may be one of the other plugin, currently unused in isolate are misbehaving, didn't think of Map extensions.

`Dart SDK version: 2.13.0 (stable) (Wed May 12 12:45:49 2021 +0200) on "macos_x64"`

I checked libphonenumber, https://github.com/emostar/flutter-libphonenumber/search?q=%22on+Map+%7B%22, no traces of map extensions.

I'll start by adding plugin registry so that isolate environment only loads the necessary plugins.  That will confirm other plugins are misbehaving.  Please correct me if my plugin registry understanding is wrong.

**Comment by nmfisher** [comment]
I don't know what libphonenumber.parse is returning, it doesn't seem to be referenced in the plugin you linked so I'm guessing it's your own code.

You're not trying to send either a null-safe Map or a Map<String, String?> are you?
```
var parsedNumber = await _libPhoneNumber.parse("+919999999999");
port.send(parsedMap!);
```

(note the exclamation mark)

**Comment by nmfisher** [comment]
Let me know if anything further required, otherwise will close this issue.

**Comment by abhinavsingh** [comment]
> I don't know what libphonenumber.parse is returning, it doesn't seem to be referenced in the plugin you linked so I'm guessing it's your own code.
> 
> You're not trying to send either a null-safe Map or a Map<String, String?> are you?
> 
> ```
> var parsedNumber = await _libPhoneNumber.parse("+919999999999");
> port.send(parsedMap!);
> ```
> 
> (note the exclamation mark)

Hey apologies, didn't get to check Github for weeks now.  I'll need to double check, but possibility is that `libphonenumber` will return optionals.  Good to close this for now, we have a TODO at our end.  I'll update if something unexpected comes up in our investigation later.  Thank you for your support!!!
