### ISSUE TITLE
How can I kill an isolate?

### ISSUE THREAD

**Issue by EdvaldoMartins** [rmawatson/flutter_isolate#79]
My question is this: How can I kill isolate after the instruction within the method is executed?

example: 

```
 var isolate = await FlutterIsolate.spawn(_run, 'id');
```

```
static void _run(String id) async { 
    await Future.delayed(Duration(seconds: 4)); 
  }
```

**Comment by nmfisher** [comment]
The README contains instructions for isolate.kill() - does this not answer your question?

**Comment by EdvaldoMartins** [comment]
> The README contains instructions for isolate.kill() - does this not answer your question?

Unfortunately no response. 
The idea is to kill isolate when the statement within the **_run** is executed and completed. 

Is that possible?

**Comment by nmfisher** [comment]
Share a SendPort/ReceivePort between your main/spawned isolate, then when the spawned isolate is finished, send a kill signal back through the SendPort so the main isolate can kill the spawned isolate.
```
void spawnIsolate(SendPort killPort) {

for(int i = 0; i < 10000; i++) {
// do some stuff
}
  killPort.send(true);
}

void main() {
  FlutterIsolate isolate;
  var port = ReceivePort();
  port.listen((msg) {
      isolate.kill()
  });
  isolate = await FlutterIsolate.spawn(spawnIsolate, port.sendPort);
}
```

Alternatively you could have a global shared isolate registry and pass through the ID when the isolate is spawned.

**Comment by EdvaldoMartins** [comment]
> Share a SendPort/ReceivePort between your main/spawned isolate, then when the spawned isolate is finished, send a kill signal back through the SendPort so the main isolate can kill the spawned isolate.
> 
> ```
> void spawnIsolate(SendPort killPort) {
>     for(int i = 0; i < 10000; i++) {
>      // do some stuff
>     }
>     killPort.send(true);
> }
> 
> void main() {
>   FlutterIsolate isolate;
>   var port = ReceivePort();
>   port.listen((msg) {
>       isolate.kill()
>   });
>   isolate = await FlutterIsolate.spawn(spawnIsolate, port.sendPort);
> }
> ```
> 
> Alternatively you could have a global shared isolate registry and pass through the ID when the isolate is spawned.

Thanks, I'll test and see if it works for me
