### ISSUE TITLE
Feature request: ability to kill all currently running processes

### ISSUE THREAD

**Issue by andersonfds** [rmawatson/flutter_isolate#95]
When you hot-reload your flutter application, the current behavior is:

- Android:
It creates another isolate (preserving the predecessor), if you hot reload multiple times it will spawn multiple isolates.

- iOS:
The application crashes

It would be neat if we had an option, maybe only available in debug, that we call and it looks up and kills any running isolate.

**Comment by JulianKeppelerCP** [comment]
Yes that would be a game changer!

**Comment by andersonfds** [comment]
My approach to tackle this was by adding an Action on my AppBar (only available in debug), which will call the kill method, but that's not optimal since I have to be aware to press that button before hot-reloading. Think I might be able to implement this feature, but only for Android, that's the reason I didn't make a PR right away

PS: Changed the title, because I didn't realize the grammar errors.

**Comment by andersonfds** [comment]
hey @JulianKeppelerCP good news! I made a PR with this feature, and it was merged (both for iOS and Android), checkout the documentation, now there's a static and awaitable method called `killAll()`. I'll be closing the PR for now.

**Comment by JulianKeppelerCP** [comment]
Awesome! Thank you so much @andersonfds
